App\Entity\EnlaceCorto:
  attributes:
    normalization_context:
      groups: [enlace_read, enlace_get]
  collectionOperations:
    post:
      method: POST
      security: is_granted("ENLACE_CREATE")
      denormalization_context:
        groups: [enlace_create]
    get:
      method: GET
#      security: is_granted("ENLACE_CREATE")
      denormalization_context:
        groups: [enlace_get]
  itemOperations:
    get:
      method: GET
      security: is_granted("ENLACE_READ", object)
    put:
      method: PUT
      security: is_granted("ENLACE_UPDATE", object)
      denormalization_context:
        groups: [enlace_update]
    delete:
      method: DELETE
      security: is_granted("ENLACE_DELETE", object)