App\Entity\EnlaceCorto:
  attributes:
    id:
      groups: [enlace_read]
    enlace:
      groups: [enlace_read, enlace_get, enlace_create, enlace_update, movement_read]
    linkRoute:
      groups: [enlace_read, enlace_get, enlace_create]
    owner:
      groups: [enlace_read, enlace_create]
